In [125]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
%matplotlib inline

In [127]:
pwd

'C:\\Users\\sonap'

In [131]:
# Step 1 : import library
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [133]:
# Step 2 : import data
salary = pd.read_csv('https://github.com/ybifoundation/Dataset/raw/main/Salary%20Data.csv')

In [134]:
salary.columns

Index(['Experience Years', 'Salary'], dtype='object')

In [135]:
y = salary['Salary']

In [139]:
X = salary[['Experience Years']]

In [141]:
X

Experience Years
0                1.1
1                1.2
2                1.3
3                1.5
4                2.0
5                2.2
6                2.5
7                2.9
8                3.0
9                3.2
10               3.2
11               3.5
12               3.7
13               3.8
14               3.9
15               4.0
16               4.0
17               4.1
18               4.3
19               4.5
20               4.7
21               4.9
22               5.1
23               5.3
24               5.5
25               5.9
26               6.0
27               6.2
28               6.5
29               6.8
30               7.1
31               7.9
32               8.2
33               8.5
34               8.7
35               9.0
36               9.5
37               9.6
38              10.3
39              10.5

In [143]:
y

0      39343
1      42774
2      46205
3      37731
4      43525
5      39891
6      48266
7      56642
8      60150
9      54445
10     64445
11     60000
12     57189
13     60200
14     63218
15     55794
16     56957
17     57081
18     59095
19     61111
20     64500
21     67938
22     66029
23     83088
24     82200
25     81363
26     93940
27     91000
28     90000
29     91738
30     98273
31    101302
32    113812
33    111620
34    109431
35    105582
36    116969
37    112635
38    122391
39    121872
Name: Salary, dtype: int64

In [145]:
salary

Experience Years  Salary
0                1.1   39343
1                1.2   42774
2                1.3   46205
3                1.5   37731
4                2.0   43525
5                2.2   39891
6                2.5   48266
7                2.9   56642
8                3.0   60150
9                3.2   54445
10               3.2   64445
11               3.5   60000
12               3.7   57189
13               3.8   60200
14               3.9   63218
15               4.0   55794
16               4.0   56957
17               4.1   57081
18               4.3   59095
19               4.5   61111
20               4.7   64500
21               4.9   67938
22               5.1   66029
23               5.3   83088
24               5.5   82200
25               5.9   81363
26               6.0   93940
27               6.2   91000
28               6.5   90000
29               6.8   91738
30               7.1   98273
31               7.9  101302
32               8.2  113812
33               8.5  111620
34               8.7  109431
35               9.0  105582
36               9.5  116969
37               9.6  112635
38              10.3  122391
39              10.5  121872

In [184]:
salary.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 40 entries, 0 to 39
Data columns (total 2 columns):
 #   Column            Non-Null Count  Dtype  
---  ------            --------------  -----  
 0   Experience Years  40 non-null     float64
 1   Salary            40 non-null     int64  
dtypes: float64(1), int64(1)
memory usage: 772.0 bytes


In [186]:
salary.describe()

Experience Years         Salary
count         40.000000      40.000000
mean           5.152500   74743.625000
std            2.663715   25947.122885
min            1.100000   37731.000000
25%            3.200000   56878.250000
50%            4.600000   64472.500000
75%            6.875000   95023.250000
max           10.500000  122391.000000

In [188]:
salary.isnull()

Experience Years  Salary
0              False   False
1              False   False
2              False   False
3              False   False
4              False   False
5              False   False
6              False   False
7              False   False
8              False   False
9              False   False
10             False   False
11             False   False
12             False   False
13             False   False
14             False   False
15             False   False
16             False   False
17             False   False
18             False   False
19             False   False
20             False   False
21             False   False
22             False   False
23             False   False
24             False   False
25             False   False
26             False   False
27             False   False
28             False   False
29             False   False
30             False   False
31             False   False
32             False   False
33             False   False
34             False   False
35             False   False
36             False   False
37             False   False
38             False   False
39             False   False

In [190]:
salary.isnull().sum()

Experience Years    0
Salary              0
dtype: int64

In [147]:
# Step 4 : train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

In [149]:
# check shape of train and test sample
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((28, 1), (12, 1), (28,), (12,))

In [151]:
# Step 5 : select model
from sklearn.linear_model import LinearRegression
model = LinearRegression()

In [153]:
model.fit(X_train,y_train)

LinearRegression()

In [155]:
model.intercept_

26596.961311068255

In [157]:
model.coef_

array([9405.61663234])

In [159]:
# Step 7 : predict model
y_pred = model.predict(X_test)

In [161]:
coeff_df = pd.DataFrame(model.coef_,X_test.columns,columns=['coefficient'])
coeff_df

coefficient
Experience Years  9405.616632

In [163]:
y_pred

array([ 90555.15441095,  59516.61952424, 106544.70268592,  64219.42784041,
        68922.23615658, 123474.81262412,  84911.78443155,  63278.86617718,
        65159.98950364,  61397.74285071,  37883.70126987,  50111.00289191])

In [165]:
# Step 8 : model accuracy
from sklearn.metrics import mean_absolute_error, mean_absolute_percentage_error, mean_squared_error, r2_score

In [167]:
mean_absolute_error(y_test,y_pred)

4005.926310168176

In [169]:
mean_absolute_percentage_error(y_test,y_pred)

0.06384602996141632

In [171]:
mse = mean_squared_error(y_test,y_pred)
mse

24141421.671440985

In [173]:
r_squared = r2_score(y_test, y_pred)
r_squared

0.960233432146844

In [175]:
from math import sqrt
rmse = sqrt(mse)
rmse

4913.39207385702

In [177]:
y_pred

array([ 90555.15441095,  59516.61952424, 106544.70268592,  64219.42784041,
        68922.23615658, 123474.81262412,  84911.78443155,  63278.86617718,
        65159.98950364,  61397.74285071,  37883.70126987,  50111.00289191])

In [179]:
df1 = pd.DataFrame({'Actual': y_test, 'Predicted' : y_pred})
df1

Actual      Predicted
29   91738   90555.154411
11   60000   59516.619524
33  111620  106544.702686
16   56957   64219.427840
19   61111   68922.236157
38  122391  123474.812624
27   91000   84911.784432
14   63218   63278.866177
17   57081   65159.989504
12   57189   61397.742851
1    42774   37883.701270
6    48266   50111.002892